services:
  rtmp:
    build: ./streaming-service
    ports:
      - "1935:1935"
      - "5173:5173"
    container_name: live_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./auth
    container_name: auth_server

